#pragma once

#define USB_SUSPEND_WAKEUP_DELAY 0

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#define ENCODER_RESOLUTION 2

#define LEADER_TIMEOUT 800
#define LEADER_PER_KEY_TIMING
