#pragma once

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#define ENCODER_RESOLUTION 2

#define SPLIT_USB_DETECT
#define NO_USB_STARTUP_CHECK
